### ISSUE TITLE
Enforce Black formatting for Python code

### ISSUE THREAD

**Issue by adrianyorke** [adrianyorke/robotframework-cookbook#29]
All Python code in the project should be formatted using Black code formatter:
https://black.readthedocs.io/en/stable/index.html

Use Black default options, i.e. no overriding recommendations for vertical hanging indents, double-quotes everywhere and maximum line length (88).  Also dispay a badge at the top of the main README showing that this project enforces Black code formatting for Python code.  Exceptions may be required for Case Study material.

GitHub Actions documentation can be found here:
https://black.readthedocs.io/en/stable/github_actions.html

**Comment by adrianyorke** [comment]
Code style black badge added to README.

**Comment by joonvena** [comment]
If this is still valid i could work on this :)

**Comment by adrianyorke** [comment]
Hi and thanks for the interest.

 Yes, this one is available and to my knowledge nobody has started work on it just yet so you are most welcome.

**Comment by joonvena** [comment]
#62

**Comment by adrianyorke** [comment]
#62 fixed this issue. Thanks again @joonvena 👍
