### ISSUE TITLE
Request for help with setting up CI

### ISSUE THREAD

**Issue by adrianyorke** [adrianyorke/robotframework-cookbook#5]
I would like to add CI to this repo, something like Travis-CI or GitHub Actions are both great.

Can you help show me the way?

**Comment by AdamHepner** [comment]
I will be taking a swing at RF + GitHub Actions soon, so I guess I can then help you out. What do you have in mind specifically?

**Comment by adrianyorke** [comment]
Thanks Adam, much appreciated.  I was thinking something simple to start with just to get CI up and running.  The contributions to this repository will mainly be markdown documents and robot scripts.  It would be good to run the robot scripts on a CI server and check that all tests are passing.  Python 3.6 and above are currently supported.  The RF requests library has a good example which uses Travis:   https://github.com/bulkan/robotframework-requests/blob/master/.travis.yml

**Comment by AdamHepner** [comment]
Well, if you're going this route, I'd take official RF repo as a starting point: https://github.com/robotframework/robotframework/blob/master/.github/workflows/acceptance_tests_cpython.yml

**Comment by adrianyorke** [comment]
Open to suggestions.

Yes, I forget that they have now added CI to the RF repo.  That was quite recent as they didn't have CI in early December when I last submitted a PR.  Do you think that's the way to go?  Makes sense as I'm sure we are trying to do the same thing, i.e. build robot scripts.

**Comment by bhirsz** [comment]
Issue is still open so I assume its still on the table :) what do you want to run in your CI? I have some experience with various CI/CD setups so I could help with it.

Usually you would like stage for linters, stage for documentation creation (if its done by script) and of course script for running the tests. The latter is tricky as you would probably mock systems ie for requests cookbock mock some API.

**Comment by adrianyorke** [comment]
Thanks @bhirsz and welcome.  I was thinking a simple test runner that runs all acceptance tests.  The scripts are currently under src folder and use .robot suffix.  Most of the recipes can be run on any machine and have no external dependencies, apart from public APIs.  Section 14 is the exception as it requires AWS creds of course, unless we run a mock AWS with something like localstack: https://github.com/localstack/localstack

Other than that, we have markdown so if there is a linter/static analysis lib for markdown format that would be cool.

**Comment by bhirsz** [comment]
What about ensuring that every cookbook contains common settings or variables? I noticed that every one is very similiar (documentation section contains some section, variables like level, recipe, category).

I will take a look into those acceptance tests in my free time and see how we could set it up.

**Comment by adrianyorke** [comment]
That's a great idea @bhirsz.  We can update the contributors guidance and explain what sections and variables are mandatory to pass CI tests.

Happy to set you up as maintainer.  No pressure, as you say this is hobby time stuff but I appreciate your interest.

**Comment by adrianyorke** [comment]
Here are some ideas for rules for all robot scripts in this repo with the exception of Case Studies:

Mandatory sections:
`*** Settings ***`
`*** Variables ***`
`*** Test Cases ***` or singular form `*** Test Case ***`

Mandatory in settings section:
`Documentation`
`Documentation` setting must contain text strings `PROBLEM:` and `DISCUSSION:` as this is the basic requirement for a recipe in the cookbook.  Perhaps a regex can help with this?

Mandatory in variables section:
`${recipe}`
`${level}`
`${category}`

`${level}` and `${category}` can also have bounds checking which will help recipe authors.

**Comment by bhirsz** [comment]
Regex would be probably enough but it's often better to use content aware parsers. Since you had well defined requirements I created external checker for Robocop: 

```
from robot.parsing.model.blocks import SettingSection, VariableSection, TestCaseSection
from robot.parsing.model.statements import Documentation, Variable
from robocop.checkers import VisitorChecker
from robocop.rules import RuleSeverity


class CaseStudiesChecker(VisitorChecker):
    rules = {
        '5501': (
            "missing-mandatory-section",
            "Missing mandatory '%s' section",
            RuleSeverity.ERROR
        ),
        '5502': (
            "missing-documentation-in-settings",
            "Missing mandatory Documentation setting in *** Settings ***",
            RuleSeverity.ERROR
        ),
        '5503': (
            "missing-mandatory-field-in-doc",
            "Missing mandatory '%s' field in documentation",
            RuleSeverity.ERROR
        ),
        '5504': (
            "missing-mandatory-variable",
            "Missing mandatory '%s' variable in *** Variables *** section",
            RuleSeverity.ERROR
        )
    }

    def __init__(self, *args):
        self.mandatory_sections = {
            '*** Settings ***': SettingSection,
            '*** Variables ***': VariableSection,
            '*** Test Cases ***': TestCaseSection
        }
        self.mandatory_variables = {
            '${recipe}',
            '${level}',
            '${category}'
        }
        self.mandatory_doc_fields = {
            'PROBLEM:',
            'DISCUSSION:'
        }
        super().__init__(*args)

    def visit_File(self, node):  # noqa
        for section_name, section_type in self.mandatory_sections.items():
            for section in node.sections:
                if isinstance(section, section_type):
                    break
            else:
                self.report("missing-mandatory-section", section_name, node=node, lineno=0)
        super().visit_File(node)

    def visit_SettingSection(self, node):  # noqa
        for statement in node.body:
            if isinstance(statement, Documentation):
                self.check_mandatory_fields_in_doc(statement)
                break
        else:
            self.report("missing-documentation-in-settings", node=node)

    def visit_VariableSection(self, node):  # noqa
        var_names = set()
        for child in node.body:
            if not isinstance(child, Variable):
                continue
            var_names.add(child.name.lower())
        for var in self.mandatory_variables:
            if var not in var_names:
                self.report("missing-mandatory-variable", var, node=node)

    def check_mandatory_fields_in_doc(self, node):
        for field in self.mandatory_doc_fields:
            if field not in node.value:
                self.report("missing-mandatory-field-in-doc", field, node=node)
```

I did run it on your code base with command:
```
robocop -r rules_by_id -r rules_by_error_type  --include 55* --ext_rules path_to_above_script.py robotframework-cookbook\src
```
I got multiple errors from "section_99" - this directory is probably meant to follow different guidelines so I modified command to ignore this directory:
```
robocop -r rules_by_id -r rules_by_error_type  --include 55* --ignore section_99\* --ext_rules path_to_above_script.py robotframework-cookbook\src
```

Final output:
```
robotframework-cookbook\src\section_14\recipe141_aws_simple_storage_service.robot:18:0 [E] 5504 Missing mandatory '${level}' variable in *** Variables *** section
robotframework-cookbook\src\section_14\recipe141_aws_simple_storage_service.robot:18:0 [E] 5504 Missing mandatory '${category}' variable in *** Variables *** section
robotframework-cookbook\src\section_14\recipe141_aws_simple_storage_service.robot:18:0 [E] 5504 Missing mandatory '${recipe}' variable in *** Variables *** section
```

Of course such detailed checks for simple repositories with mostly examples is probably overkill but it's always fun for me to setup various QA measures ;)

**Comment by bhirsz** [comment]
> That's a great idea @bhirsz. We can update the contributors guidance and explain what sections and variables are mandatory to pass CI tests.
> 
> Happy to set you up as maintainer. No pressure, as you say this is hobby time stuff but I appreciate your interest.

It would be helpfull, I have basic setup locally but I need extra permissions to set up Actions in repo

**Comment by adrianyorke** [comment]
"bhirsz has been added as a collaborator on the repository."

**Comment by adrianyorke** [comment]
class CaseStudiesChecker(..) could be named RecipeChecker(..).  Case Study material is uploaded to section_99 "as is" so is unlikely to have the recipe format or headers.

**Comment by adrianyorke** [comment]
It would be helpful to have a label at the top of the main README showing current status of Continuous Integration:
![image](https://user-images.githubusercontent.com/30093433/93743852-7a916980-fbf9-11ea-82ab-609547f00f8b.png)

**Comment by bhirsz** [comment]
> It would be helpful to have a label at the top of the main README showing current status of Continuous Integration:
> ![image](https://user-images.githubusercontent.com/30093433/93743852-7a916980-fbf9-11ea-82ab-609547f00f8b.png)

I will add it together with actions

**Comment by bhirsz** [comment]
I added initial version of CI:
https://github.com/adrianyorke/robotframework-cookbook/pull/26/checks
I'm going to clean up it a bit and fix issues later. But it's  almost done - most tests are passing. 
Do you want for Robocop to run only with rules mentioned in this thread or all rules available? I can set it up that it will not fail the build in case Robocop returns any issue (for now)

**Comment by adrianyorke** [comment]
Thanks @bhirsz, it looks great.  I think Robocop can rule ALL rules but maybe don't fail if it is only a warning message?  Hard errors should fail the build though.

**Comment by bhirsz** [comment]
> Thanks @bhirsz, it looks great and quite satisfactory for the first version. Robocop can check ALL rules but maybe don't fail if it is only a warning message? Hard errors should fail the build though.

Sure, this argument should cover this (any number of Warning should not fail the build):
```
--configure return_status:quality_gate:W=-1
```

**Comment by adrianyorke** [comment]
How about the threshold parameter, would this be a clearer way of stating which errors we are ignoring?

From the Robocop documentation:
```
- filtering out all rules below given severity level::
     --threshold E
```

**Comment by bhirsz** [comment]
The difference between those two is that the first one (return_status:quality_gate) will run all rules but only fail on configured levels and --threshold will actually filter out and not run everything below given severity level. So only rules with severity Error will be executed & reported. Is it what you want?

**Comment by adrianyorke** [comment]
I like your original suggestion in that case, i.e. run all the rules but only fail those with severity Error.

**Comment by adrianyorke** [comment]
@all-contributors please add @bhirsz for Code, Documentation, Maintenance, Review
