### ISSUE TITLE
Add instructions how to install and use cookbook

### ISSUE THREAD

**Issue by adrianyorke** [adrianyorke/robotframework-cookbook#77]
I have assumed since the beginning of this project that those interested in _Robot Framework - Cookbook_ know how to clone a github repo, install the required Python libs and run the recipes, but that may not be the case for everybody.

Add Installation and Usage section(s) to README explaining how to set up this repo locally, install packages and execute the Robot Framework recipes.

Also explain that libs can be installed using the relevant _requirements*.txt_ document located in the _tests_ folder.

**Comment by jepoy92** [comment]
Hello, I'd like to tackle this issue. May I be assigned? Also, when would you like this issue to be completed?

**Comment by adrianyorke** [comment]
Hi @jepoy92j, You are most welcome, thanks for the kind offer. This is not a critical issue so it's really up to you. Aim to complete it before October though as we will have lots of interest in our backlog for the Hacktoberfest month.

**Comment by jepoy92** [comment]
Awesome, thanks so much!

**Comment by jepoy92** [comment]
Hello, before I begin I had some content related questions. I see the structure of your table of contents and I have also seen that you have a few guides on how to install Robot Framework, do you want me to add these instructions to the README or shall I find a related article and link it in the table of contents?

**Comment by jepoy92** [comment]
I have a draft of my addition ready but I'm having trouble creating a branch and PR request due to permissions. I'm not clear on what your process is for submitting PRs, please let me know what I can submit! Hope you've been having a great weekend!

**Comment by adrianyorke** [comment]
The process is similar to most FOSS projects. You clone the latest repo (git clone) then in the shell create a branch from master (git checkout -b <YOUR_BRANCH_NAME>).

The branch name is your choice - here are a couple of examples:
- update-readme-with-usage-instructions
- fix-issue-77

When you have made your changes you use `git add .`, `git commit -m <YOUR_MESSAGE>`, `git push origin <YOUR_BRANCH_NAME>`

Let me know if you need more guidance but don't worry if you get it wrong - I can explain more in the PR chat.

**Comment by jepoy92** [comment]
I've been trying to but I keep getting the following error message in my terminal:
![image](https://github.com/adrianyorke/robotframework-cookbook/assets/65995065/d7ddb23f-80ad-4f6c-8436-89213841ecc1)

**Comment by adrianyorke** [comment]
This is all you need:
`git push origin feature-fix-issue-77`

So you are saying push to origin (cookbook github repo) my local branch feature-fix-issue-77.

**Comment by adrianyorke** [comment]
Your git add/git commit responded "nothing to commit" - have you made changes to the README in that local location?

**Comment by adrianyorke** [comment]
Ah yes, you don't have permissions to push directly to cookbook - that's only me. You will need to create what is know as a fork of the cookbook repository in your own github account then you work on the fork repo and push your branch to your fork.

The final step is to create a pull request to ask for your branch on your fork repo, to be merged into the main cookbook repo.

Does that make sense?

You can look at the history of pull requests to see how other contributors have been doing this.

**Comment by adrianyorke** [comment]
I will create a new issue to document this guidance for contributors.

**Comment by adrianyorke** [comment]
You create a fork of this repository by selecting "Create a new fork" under the Fork drop-down:
![image](https://github.com/adrianyorke/robotframework-cookbook/assets/30093433/0f298c9e-b257-46b7-b92e-9205940f609f)

**Comment by adrianyorke** [comment]
I can see you have already successfully created a fork 5 days ago so you clone that and push your branch to your fork:
![image](https://github.com/adrianyorke/robotframework-cookbook/assets/30093433/d4a7f8f4-dca2-4735-8888-32147e51a65d)

**Comment by jepoy92** [comment]
Thank you for the direction, i was able to create a pull request and am awaiting your review.
