### ISSUE TITLE
Create contibuting guidelines to explain how to submit code and documentation updates

### ISSUE THREAD

**Issue by adrianyorke** [adrianyorke/robotframework-cookbook#78]
It would be helpful to explain the contributing process and guide contributors so they can effectively submit their work.

Consider:

- Development and testing standards that should be followed
- Working on a fork repo
- Cloning repo
- Branch naming
- Pull request usage
- Recognition in Contributors section

**Comment by sarafurd** [comment]
Please assign this to me

**Comment by adrianyorke** [comment]
Welcome @sarafurd, and thanks for the kind offer.

**Comment by adrianyorke** [comment]
If you are looking for ideas, I found another excellent CONTRIBUTING document using markdown:
https://github.com/git-ecosystem/git-credential-manager/blob/main/CONTRIBUTING.md

I like the layout of this document - it's clean and clear what steps to follow:
1. Introduction
2. Start with an issue
3. Submitting a pull request (explains how contributors should start with fork and clone of main repo)

**Comment by adrianyorke** [comment]
Also check out the discussion on this recent issue - I explain in detail how to contribute to this project in the comments:
https://github.com/adrianyorke/robotframework-cookbook/issues/77

**Comment by sarafurd** [comment]
are you specific on how they should name the branch?

**Comment by adrianyorke** [comment]
No, they can even use "master" as it's the branch in their fork repo.

Here are some examples that have been used in the past:
![image](https://github.com/adrianyorke/robotframework-cookbook/assets/30093433/e0d438d3-fbd5-422a-95e8-2a2663897b13)

**Comment by sarafurd** [comment]
# Contributing

Anyone is welcome to contribute by making a pull request
- Find an [issue](https://github.com/adrianyorke/robotframework-cookbook/issues) to work on 
- Fork the project
- After you've cloned your fork of the project, you will need to make a branch
```
$ git checkout -b name-of-branch

```
- Make any changes, save your work, and make the necessary commits 
    - Example: fixes-issue-xxx or feature-issue-xxx
    - Use present tense  

```
$ git add.
$ git commit -m "fixes-issue-xxx" 
$ git status

# Push the code to the branch you made
$ git push origin name-of-your-branch

```
- Once you've pushed your branch, don't forget to make a pull request into the `main` branch.

**Comment by adrianyorke** [comment]
Thanks, looks good. A couple of minor updates:
1. For the git add instruction, there needs to be a space between 'add' and '.', like this:
$ git add .
2. Change `main` branch to `master` for this repo

**Comment by sarafurd** [comment]
Made the changes

**Comment by adrianyorke** [comment]
Cool, no that's it for the CONTRIBUTING.md. You can now follow your own instructions:
1. fork this repo
2. create your branch on your fork
3. git add .
4. git commit -m "bla bla"
5. git push origin <YOUR_BRANCH_NAME>
6. Finally, create pull request here in the main project requesting me to merge of your fork branch with master.

Thanks for the effort - I will add you to the contributors after I merge your PR.
